sonar.projectKey=TomasRicaurte_Integracion_continua
sonar.organization=tomasricaurte

sonar.projectName=Integracion_continua
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=test

sonar.test.inclusions=test/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8